#!/bin/bash

while [ TRUE ];do
    if [ `nmcli networking connectivity` = 'full' ]
    then
        python3 presync.py && \
            mbsync -a && \
            python3 postsync.py
    fi
    read -t 120
done
