#!/bin/bash

while [ TRUE ];do
    if [ `nmcli networking connectivity` = 'full' ]
    then
        python presync.py && \
            mbsync -a && \
            python postsync.py
    fi
    read -t 120
done
